<<<<<<< HEAD
title: Programiranje 1
author: Matija Pretnar
exclude_patterns:
  - odlozisce/*
repository:
  url: 'https://github.com/matijapretnar/programiranje-1'
  book_path: zapiski
  branch: zapiski
launch_buttons:
  binderhub_url: 'https://mybinder.org'
=======
title: Programiranje 1
author: Matija Pretnar
exclude_patterns:
  - odlozisce/*
repository:
  url: 'https://github.com/matijapretnar/programiranje-1'
  book_path: zapiski
  branch: zapiski
only_build_toc_files: true
<<<<<<< HEAD
>>>>>>> 563fcef635626a6229f5f57b6fec9f6de2e4c063
=======
execute:
  exclude_patterns:
    - 'dn-*.ipynb'
<<<<<<< HEAD
>>>>>>> 647cad05123e5ee1a62952360459a2f8752faa5d
=======
sphinx:
  extra_extensions:
    - sphinx_proof
>>>>>>> d531cff0f46630f8b7083d24683cd8cf6d321896
